<?php

/**
 * @file
 * Default template for HTML Mail
 *
 * DO NOT EDIT THIS FILE. Copy it to your theme directory, and edit the copy.
 *
 * ========================================================= Begin instructions.
 *
 * When formatting an email message with a given $module and $key, [1]HTML
 * Mail will use the first template file it finds from the following list:
 *  1. htmlmail--$module--$key.tpl.php
 *  2. htmlmail--$module.tpl.php
 *  3. htmlmail.tpl.php
 *
 * For each filename, [2]HTML Mail looks first in the chosen Email theme
 * directory, then in its own module directory, before proceeding to the
 * next filename.
 *
 * For example, if example_module sends mail with:
 * drupal_mail("example_module", "outgoing_message" ...)
 *
 *
 * the possible template file names would be:
 *  1. htmlmail--example_module--outgoing_message.tpl.php
 *  2. htmlmail--example_module.tpl.php
 *  3. htmlmail.tpl.php
 *
 * Template files are cached, so remember to clear the cache by visiting
 * admin/config/development/performance after changing any .tpl.php files.
 *
 * The following variables available in this template:
 *
 * $body
 *        The message body text.
 *
 * $module
 *        The first argument to [3]drupal_mail(), which is, by convention,
 *        the machine-readable name of the sending module.
 *
 * $key
 *        The second argument to [4]drupal_mail(), which should give some
 *        indication of why this email is being sent.
 *
 * $message_id
 *        The email message id, which should be equal to
 *        "{$module}_{$key}".
 *
 * $headers
 *        An array of email (name => value) pairs.
 *
 * $from
 *        The configured sender address.
 *
 * $to
 *        The recipient email address.
 *
 * $subject
 *        The message subject line.
 *
 * $body
 *        The formatted message body.
 *
 * $language
 *        The language object for this message.
 *
 * $params
 *        Any module-specific parameters.
 *
 * $template_name
 *        The basename of the active template.
 *
 * $template_path
 *        The relative path to the template directory.
 *
 * $template_url
 *        The absolute URL to the template directory.
 *
 * $theme
 *        The name of the Email theme used to hold template files. If the
 *        [5]Echo module is enabled this theme will also be used to
 *        transform the message body into a fully-themed webpage.
 *
 * $theme_path
 *        The relative path to the selected Email theme directory.
 *
 * $theme_url
 *        The absolute URL to the selected Email theme directory.
 *
 * $debug
 *        TRUE to add some useful debugging info to the bottom of the
 *        message.
 *
 * Other modules may also add or modify theme variables by implementing a
 * MODULENAME_preprocess_htmlmail(&$variables) [6]hook function.
 *
 * References
 *
 * 1. http://drupal.org/project/htmlmail
 * 2. http://drupal.org/project/htmlmail
 * 3. http://api.drupal.org/api/drupal/includes--mail.inc/function/drupal_mail/7
 * 4. http://api.drupal.org/api/drupal/includes--mail.inc/function/drupal_mail/7
 * 5. http://drupal.org/project/echo
 * 6. http://api.drupal.org/api/drupal/modules--system--theme.api.php/function/hook_preprocess_HOOK/7
 *
 * =========================================================== End instructions.
 */
  $template_name = basename(__FILE__);
  $current_path = realpath(NULL);
  $current_len = strlen($current_path);
  $template_path = realpath(dirname(__FILE__));
  if (!strncmp($template_path, $current_path, $current_len)) {
    $template_path = substr($template_path, $current_len + 1);
  }
  $template_url = url($template_path, array('absolute' => TRUE));
?>
<body style="margin: 0; background: #000;">
  <div style="padding: 10px; background: #000; color: #D8D8D8; font-family: Verdana, sans-serif; font-size: 11px; text-align: center;">
    <style type="text/css"><!--
    div:after {{
      clear: both;
      display: block;
      visibility: hidden;
      height: 0;
      content: ".";
    }}
    * html div {{
      height: 1%;
    }}
    --></style>
    <div style="position: relative; margin: 0 auto; width: 600px; background: #E7E7E7; color: #494949; text-align: left;">

      <h1 style="margin: 0;"><img style="display: block;" src="{4}boven.jpg" alt="Beeld en Geluid" width="600" height="75"></h1>

      <div style="line-height: 1.5;">

        <h2 style="margin: 23px 60px 12px 28px; color: #494949; font-family: 'Arial Narrow', Arial, sans-serif; font-size: 22px; font-weight: bold;">
        BEELD EN GELUID SCRIPTMACHINE</h2>

        <p style="margin: 1em 60px 1em 28px;">
        Hallo <?php echo $params['to_name']; ?>,</p>

        <p style="margin: 1em 60px 1em 28px;">
        <?php echo $params['from_name']; ?> heeft een script gemaakt op de educatie-website van Beeld en Geluid en wil deze graag aan je laten zien!
        </p>
         <p style="margin: 1em 60px 1em 28px;">
        Bij deze mail schreef <?php echo $params['from_name']; ?> je de volgende persoonlijke boodschap:
        </p>
        <p style="margin: 1em 60px 1em 28px; width: 100%; overflow: auto; white-space: pre"><?php echo $params['message']; ?></p>
  	  <p style="margin: 1em 60px 1em 28px;">
          <a style="color: #0080CE; font-weight: bold; text-decoration: none;" href="<?php echo $params['script_url']; ?>">Bekijk het script</a>
  	  </p>
        <p style="margin: 1em 60px 0.5em 28px;">
          Nieuwsgierig geworden? Zelf een script maken met onze
          Scriptmachine?<br>Bezoek dan de website van Beeld en Beluid!
  		</p>
        <p style="margin: 1em 60px 1em 28px;">
        <a style="color: #0080CE; font-weight: bold; text-decoration: none;" href="http://www.beeldengeluid.nl/">
          Ga naar de Beeld en Geluid website <img style="border: none;" src="{4}bullet-blue.gif" alt="" width="19" height="10"></a>
        </p>
        <p style="margin: 1em 60px 1em 28px;">Tot ziens,<br>
          Beeld en Geluid.
        </p>

      </div>
      <div style="padding: 9px; background: #4D4D4D; color: #D8D8D8; font-size: 10px; font-weight: bold;">
          <span style="float: right;">&copy; Beeld en Geluid 2012</span>
      </div>
    </div>
  </div>
</body>
