<?php
define('CONTENT_TYPE_MEDIA', 'media');
define('CONTENT_TYPE_TEXT', 'text');
define('CONTENT_TYPE_SEARCH_RESULT', 'search_result');
define('CONTENT_TYPE_QUOTE', 'quote');
define('CONTENT_TYPE_BANNER', 'banner');

/***************************************************************
 * Field Type API hooks
 ***************************************************************/
 
/**
 * Implement hook_field_info().
 */
function bg_reference_field_info() {
  return array(
    'bg_reference' => array(
      'label'             => t('Referenced content'),
      'description'       => t('Stores a reference to content.'),
      'default_widget'    => 'bg_referencefield',
      'default_formatter' => 'bg_referenceformat',
    ),
  );
}

/**
 * Implement hook_field_schema().
 */
function bg_reference_field_schema($field) {
  $columns = array(
    'type' => array(
      'type'      => 'varchar',
      'length'    => 32,
      'not null'  => TRUE
    ),
    'content' => array(
      'type'      => 'text',
      'not null'  => TRUE
    ),
    'pos_x' => array(
      'type' => 'int', 
      'unsigned' => FALSE, 
      'not null' => TRUE, 
      'default' => 0,
    ),
    'pos_y' => array(
      'type' => 'int', 
      'unsigned' => FALSE, 
      'not null' => TRUE, 
      'default' => 0,
    ),
    'width' => array(
      'type' => 'int', 
      'unsigned' => TRUE, 
      'not null' => TRUE, 
      'default' => 1,
    ),
    'height' => array(
      'type' => 'int', 
      'unsigned' => TRUE, 
      'not null' => TRUE, 
      'default' => 1,
    ),
  );
  
  return array('columns' => $columns);
}

/**
 * Implement hook_field_validate().
 */
function bg_reference_field_validate($obj_type, $object, $field, $instance, $langcode, &$items, &$errors) {
  /*foreach($items as $delta => $item) {
    if(isset($item['bg_reference'])) {
      if(! preg_match('@^#[0-9a-f]{6}$@', $item['rgb'])) {
        $errors[$field['field_name']][$langcode][$delta][] = array(
          'error' => 'bg_reference_invalid',
          'message' => t('Color must be an HTML spec'),
        );
      }
    }
  }*/
}

/**
 * Implement hook_field_validate().
 */

/**
 * Implement hoo_field_is_empty().
 */
function bg_reference_field_is_empty($item, $field) {
  //return empty($item['bg_reference']);
}

/***********************************************************************
 *  Field Type API: Formatter
 **********************************************************************/
 
/**
 * Implement hook_field_formatter_info().
 */
function bg_reference_field_formatter_info() {
  /*return array(
    'colorpicker_helloworld' => array(
      'label' => t('"Hello ,World" In color'),
      'field types' => array('colorpicker_rgb'),
    ),
  );*/
}
 
/**
 * Implements hook_field_formatter_view().
 */
function bg_reference_field_formatter_view($object_type, $object, $field, $instance, $langcode, $items, $display) {
  $element = array();
  
  /*if($display['type']=='colorpicker_helloworld') {
      foreach ($items as $delta => $item) {
        $element[$delta] = '<p style="color: ' . $items[0]['rgb']. '">Hello, World</p>';
      }
  }*/
  
  return $element;
}
/**************************************************************************
 * Field Type API: Widget
 **************************************************************************/
 
/**
 * Implement hook_field_widget_info().
 */
function bg_reference_field_widget_info() {
  return array(
    'bg_referencefield' => array(
      'label'       => t('Referenced content'),
      'field types' => array('bg_reference'),
    )
  );
}

/**
 * Implement hook_field_widget().
 *
 * This widget displayed three text fields\, one each for red, green,
 * and blue. However, the field type defines a single text column,
 * rgb, which needs an HTML color spec. Define an element validate 
 * handler that converts our r, g, and b fields into a simulaed single
 * 'rgb' form element.
 */
function bg_reference_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta = 0) {
  $element = array(
    '#type' => 'fieldset',
    // Cinvert during validation.
    '#element_validate' => array('_bg_reference_validate'),
    // TODO: This should not be necessary.
    '#langcode' => $langcode,
    'type' => array(
      '#type'     => 'select',
      '#title'    => t('Content type'),
      '#options'  => array(
        CONTENT_TYPE_MEDIA          => t('Media'),
        CONTENT_TYPE_TEXT           => t('Text'),
        CONTENT_TYPE_SEARCH_RESULT  => t('Search result'),
        CONTENT_TYPE_QUOTE          => t('Quote'),
        CONTENT_TYPE_BANNER         => t('Banner')
      ),
      '#default_value' => isset($items[$delta]['type']) ? $items[$delta]['type'] : CONTENT_TYPE_TEXT,
    ),
    'content' => array(
      '#type'   => 'textarea',
      '#title'  => t('Content'),
      '#default_value' => isset($items[$delta]['content']) ? $items[$delta]['content'] : '',
    ),
    'pos_x' => array(
      '#type'   => 'textfield',
      '#title'  => t('X position'),
      '#default_value' => isset($items[$delta]['pos_x']) ? $items[$delta]['pos_x'] : 0,
    ),
    'pos_y' => array(
      '#type'   => 'textfield',
      '#title'  => t('Y position'),
      '#default_value' => isset($items[$delta]['pos_y']) ? $items[$delta]['pos_y'] : 0,
    ),
    'width' => array(
      '#type'   => 'textfield',
      '#title'  => t('Width'),
      '#default_value' => isset($items[$delta]['width']) ? $items[$delta]['width'] : 1,
    ),
    'height' => array(
      '#type'   => 'textfield',
      '#title'  => t('Height'),
      '#default_value' => isset($items[$delta]['height']) ? $items[$delta]['height'] : 1,
    ),
  );
  
  return $element;
}

/**
 * Convert form elements r, g, and b into a single rgb HTML spec. We
 * should also perform widget-level validation here to get per-color
 * error reporting, but field-level validation is good enough for now.
 */
function _bg_reference_validate($element, &$form_state) {
  if(preg_match('/(?P<name>\w+)\[(?P<langcode>\w+)\]\[(?P<id>\d+)\]/', $element['type']['#name'], $field)) {
    if (isset($form_state['values'][$field['name']][$field['langcode']][$field['id']])) {
      $values = $form_state['values'][$field['name']][$field['langcode']][$field['id']];
      
      form_set_value($element, $values, $form_state);
    }
  }
}

/**
 * Implement hook_field_error().
 */
/*function colorpicker_field_widget_error($element, $error) {
  switch ($error['error']) {
    case 'colorpicker_invalid':
      form_error($element, $error['message']);
    break;
  }
}
*/
