<?php

/**
 * Implements hook_field_extra_fields().
 */
function bg_verbreding_field_extra_fields() {
  $extra['node']['media'] = array(
    /*
    'form' => array(
      'choice_wrapper' => array(
        'label' => t('Poll choices'), 
        'description' => t('Poll choices'), 
        'weight' => -4,
      ), 
      'settings' => array(
        'label' => t('Poll settings'), 
        'description' => t('Poll module settings'), 
        'weight' => -3,
      ),
    ),
    */ 
    'display' => array(
      'bg_fb_like' => array(
        'label' => t('Facebook Like'), 
        'description' => t('Like button for Facebook'), 
        'weight' => 10,
      ),
      'bg_share_online' => array(
        'label' => t('Share online'), 
        'description' => t('Share with online services'), 
        'weight' => 11,
      ),
      'bg_embed' => array(
        'label' => t('Embed'), 
        'description' => t('Embed'), 
        'weight' => 12,
      ),
    ),
  );

  return $extra;
}

/**
 * Implements hook_node_view().
 */
function bg_verbreding_node_view($node, $view_mode, $langcode) {

  $href = entity_uri('node', $node);
  
  // Isn't there a way to do this without hard-coding language codes?
  $locale = 'nl_NL'; 
  switch ($langcode) {
    case 'en':
      $locale = 'en_US';
  }
 
  $node->content['bg_fb_like'] = array(
    '#type' => 'markup',
    '#prefix' => '<div class="verbreding-item-fb-like verbreding-item"><div class="verbreding-item-inner">',
    '#markup' => '<fb:like href="' . $href . '" send="false" width="220" show_faces="false" colorscheme="dark" font="verdana"></fb:like>',
    '#suffix' => '</div></div>',
  );

  $node->content['bg_share_online'] = array(
    '#type' => 'markup',
    '#prefix' => '<div class="verbreding-item-share-online verbreding-item"><div class="verbreding-item-inner">',
    '#markup' => 'bar',
    '#suffix' => '</div></div>',
  );
    
  $node->content['bg_embed'] = array(
    '#type' => 'markup',
    '#prefix' => '<div class="verbreding-item-embed verbreding-item"><div class="verbreding-item-inner">',
    '#markup' => 'foo',
    '#suffix' => '</div></div>',
  );
}

function bg_verbreding_node_view_alter($build) {
  $build['bg_share_online']['#markup'] = render($build['links']);
  $build['bg_share_online']['#markup'] = 'baz';
  unset($build['links']);
  //dsm($build);
}
