<?php

/**
 * Implements hook_field_extra_fields().
 */
function bg_verbreding_field_extra_fields() {
  $extra['node']['media'] = array(
    'display' => array(
      'bg_fb_like' => array(
        'label' => t('Facebook Like'), 
        'description' => t('Like button for Facebook'), 
        'weight' => 10,
      ),
      'bg_share_online' => array(
        'label' => t('Share online'), 
        'description' => t('Share with online services'), 
        'weight' => 11,
      ),
      'bg_embed' => array(
        'label' => t('Embed'), 
        'description' => t('Embed'), 
        'weight' => 12,
      ),
    ),
  );

  return $extra;
}

/**
 * Implements hook_node_view().
 */
function bg_verbreding_node_view($node, $view_mode, $langcode) {

  if ($node->type == 'media') {
    $href = entity_uri('node', $node);
    
    // Isn't there a way to do this without hard-coding language codes?
    $locale = 'nl_NL'; 
    switch ($langcode) {
      case 'en':
        $locale = 'en_US';
        break;
    }
   
    $node->content['bg_fb_like'] = array(
      '#type' => 'markup',
      '#prefix' => '<div class="verbreding-item-fb-like verbreding-item"><div class="verbreding-item-inner">',
      '#markup' => '<fb:like href="' . $href . '" layout="button_count" send="false" width="220" show_faces="false" colorscheme="dark" font="verdana"></fb:like>',
      '#suffix' => '</div></div>',
    );
  
    $node->content['bg_share_online'] = array(
      '#type' => 'markup',
      '#prefix' => '<div class="verbreding-item-share-online verbreding-item"><div class="verbreding-item-inner">' . t('<strong>Share</strong> this clip'),
      '#markup' => '',
      '#suffix' => '</div></div>',
    );
      
    $node->content['bg_embed'] = array(
      '#type' => 'markup',
      '#prefix' => '<div class="verbreding-item-embed verbreding-item"><div class="verbreding-item-inner">',
      '#markup' => 'Embed',
      '#suffix' => '</div></div>',
    );
  }
}

function bg_verbreding_node_view_alter(&$build) {
  if (isset($build['bg_share_online']) && isset($build['links'])) {
    $build['bg_share_online'] += $build['links'];
    unset($build['links']);
  }
}


function bg_verbreding_embed_view($node) {
  return node_view($node, 'embed');
}

/**
 * Implements hook_menu().
 */
function bg_verbreding_menu() {
  $items = array();
  
  $items['node/%node/embed'] = array(
    'title' => 'Embedded',
    'page callback' => 'bg_verbreding_embed_view',
    'page arguments' => array(1),
    'access callback' => 'node_access',
    'access arguments' => array('view', 1),
    'type' => MENU_CALLBACK,
  );
  
  return $items;
}

/**
 * Implements hook_entity_info_alter().
 * Add a view mode for embedded nodes.
 */
function bg_verbreding_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['embed'] = array(
    'label' => t('Embedded'),
    'custom settings' => FALSE,
  );
}

