<?php
/**
 * Implements hook_feeds_plugins().
 */
function bg_feeds_file_processor_feeds_plugins() {
  $info = array();
  $info['FeedsFileProcessor'] = array(
    'name' => 'File processor',
    'description' => 'Create and update files.',
    'help' => 'Create and update files from parsed content.',
    'handler' => array(
      'parent' => 'FeedsProcessor',
      'class' => 'FeedsFileProcessor',
      'file' => 'FeedsFileProcessor.inc',
      'path' => drupal_get_path('module', 'bg_feeds_file_processor'),
    ),
  );
  return $info;
}

function bg_feeds_file_processor_file_insert($file) {
  // File produced by source.
  feeds_item_info_insert($file, $file->fid);
}

function bg_feeds_file_processor_file_update($file) {
  // File produced by source.
  feeds_item_info_save($file, $file->fid);
}

function bg_feeds_file_processor_file_delete($file) {
  // File produced by source.
  db_delete('feeds_item')
    ->condition('entity_type', 'file')
    ->condition('entity_id', $file->fid)
    ->execute();
}