<?php

  define('GRIDUI_DEBUG', true);

  function gridui_form_alter(&$form, &$form_state, $form_id) {

    if(GRIDUI_DEBUG) dsm('Doing gridui_form_alter');
    if(GRIDUI_DEBUG) dsm($form);

    if($form_id == "dossier_node_form") {
      if(GRIDUI_DEBUG) dsm('Injecting JavaScript');

      // Inject static files necessary into page
      drupal_add_js(drupal_get_path('module', 'gridui') . '/js/gridui.js', array('type' => 'file',
                                                                                 'scope' => 'footer',
                                                                                 'weight' => 5));
      drupal_add_css(drupal_get_path('module', 'gridui') . '/css/gridui.css');

      if(GRIDUI_DEBUG) dsm('Adding gridui frame');
      // Add a drawing frame to the form
      $form['gridui'] = array('#markup' => '<div id="gridui-frame"></div>');

      // Set position fields to be hidden
      /*
      foreach($form["field_referenced_content"]["nl"] as $key => $value) {
        if(is_numeric($key)) {
          if(GRIDUI_DEBUG) dsm("Hiding positions of {$key}");
          $form["field_referenced_content"]["nl"][$key]["pos_x"]["#type"] = "hidden";
          $form["field_referenced_content"]["nl"][$key]["pos_y"]["#type"] = "hidden";
        }
      }
      */
      
    }
  }

?>
