<?php
define('PERMISSION_ACCESS_SCRIPTMACHINE_API', 'access scriptmachine api');

/**
 * Implementation of hook_permission()
 */
function bg_scriptmachine_permission() {
  return array(
    PERMISSION_ACCESS_SCRIPTMACHINE_API => array(
      'title' => t('Access Script Machine'),
      'description' => t('Access API of the Script Machine.'),
    ),
  );
}

/**
 * Implementation of hook_menu()
 */
function bg_scriptmachine_menu() {
  $items = array();

  $items['api/scriptmachine'] = array(
    'page callback'     => 'bg_scriptmachine_api',
    'page arguments'    => array(2),
    'access callback'	=> TRUE,
    'type'              => MENU_CALLBACK,
  );
  $items['admin/config/scriptmachine'] = array(
    'title'             => 'Scriptmachine Settings',
    'page callback'     => 'drupal_get_form',
    'page arguments'    => array('bg_scriptmachine_admin_settings'),
    'type'              => MENU_NORMAL_ITEM,
    'access arguments'  => array('administer site configuration'),
  );

  return $items;
}

function bg_scriptmachine_admin_settings() {
  $form = array();

  $form['bg_scriptmachine_url'] = array(
    '#type' => 'textfield',
    '#title' => 'Scriptmachine URL',
    '#default_value' => variable_get('bg_scriptmachine_url',''),
  );

  return system_settings_form($form);
}

/**
 * Scriptmachine API call handler
 * Handles calls to the scriptmachine API from Flash.
 * @param String $action
 */
function bg_scriptmachine_api($action) {
  if (user_access(PERMISSION_ACCESS_SCRIPTMACHINE_API)) {
    $api_action = '_bg_scriptmachine_api_' . $action;

    if (function_exists($api_action)) {
      try {
        $xml_response = $api_action();
      }
      catch (Exception $e) {
        $xml_response = _bg_scriptmachine_create_error_document($e->getMessage(), $e->getCode());
      }
    }
    else {
      // Throw error
      $xml_response = _bg_scriptmachine_create_error_document('API is not avaialble', '1001');
    }
  }
  else {
    // Throw error
    $xml_response = _bg_scriptmachine_create_error_document('Unauthorized', '1002');
  }

  header('Content-Type: application/xml');
  echo $xml_response->saveXML();
  exit;
}

function bg_scriptmachine_mail($key, &$message, $params) {
  switch($key) {
    case 'notify':
      $langcode = $message['language']->language;
      $message['subject'] = t('A message from !name', array('!name' => $params['from_name']), array('langcode' => $langcode));
      break;
  }
}

function _bg_scriptmachine_api_scripts() {
  $xml_response = new DOMDocument('1.0', 'UTF-8');
  $uid = $_GET['user'];

  if (!is_numeric($uid)) {
    throw new Exception('Missing or invalid userid argument', 4);
  }
  else {
    $query = "SELECT `fid` FROM {bg_scriptmachine} WHERE `uid` = :uid";
    $file = file_load(db_query($query, array(':uid' => $uid))->fetchColumn());

    if ($file === FALSE || !file_exists($file_path = drupal_realpath($file->uri))) {
      throw new Exception('Missing user document, create a new one if you please.', 8);
    }
    else {
      $xml_response->load($file_path);
    }
  }

  return $xml_response;
}

function _bg_scriptmachine_api_store() {
  $document = new DOMDocument('1.0', 'UTF-8');
  $xml_response = _bg_scriptmachine_create_ok_document();
  $uid = $_GET['user'];

  if (!is_numeric($uid)) {
    throw new Exception('Missing or invalid userid argument', 4);
  }
  else {
    $document->load('php://input');

    $query = "SELECT `fid` FROM {bg_scriptmachine} WHERE `uid` = :uid";
    $original_file = file_load(db_query($query, array(':uid' => $uid))->fetchColumn());

    if ($original_file === FALSE || !file_exists(drupal_realpath($original_file->uri))) {
      $path = file_build_uri('user/' . $uid . '/scriptmachine.xml');
      file_prepare_directory(drupal_dirname($path), FILE_CREATE_DIRECTORY | FILE_MODIFY_PERMISSIONS);
    }
    else {
      $path = $original_file->uri;
    }

    $new_file = file_save_data($document->saveXML(), $path, FILE_EXISTS_REPLACE);

    if ($new_file === FALSE) {
      throw new Exception('Could not create script', 8);
    }
    else if ($original_file === FALSE) {
      $fields = array('uid' => $uid, 'fid' => $new_file->fid, 'created' => REQUEST_TIME, 'changed' => REQUEST_TIME);
      db_insert('bg_scriptmachine')
        ->fields($fields)
        ->execute();
    }
    else {
      $fields = array('changed' => REQUEST_TIME);
      db_update('bg_scriptmachine')
        ->condition('uid', $uid)
        ->condition('fid', $new_file->fid)
        ->fields($fields)
        ->execute();
    }
  }

  return $xml_response;
}

function _bg_scriptmachine_api_notify() {
  global $language;
  $xml_response = _bg_scriptmachine_create_ok_document();
  $params = array();

  $params['uid'] = $_POST['uID'];
  $params['sid'] = $_POST['sID'];

  $params['from_name'] = $_POST['namefrom'];
  $params['from_email'] = $_POST['emailfrom'];

  $params['to_name'] = $_POST['namefriend'];
  $params['to_email'] = $_POST['emailfriend'];

  $params['message'] = $_POST['message'];

  if (!is_numeric($params['uid'])) {
    throw new Exception('Missing or invalid userid argument', 4);
  }
  else if (empty($params['from_email'])) {
    throw new Exception('Afzender adres ontbreekt');
  }
  else if (empty($params['to_email'])) {
    throw new Exception('Ontvanger adres ontbreekt.');
  }
  else {
    $params['script_url'] = url(variable_get('bg_scriptmachine_url', ''), array('absolute' => TRUE, 'query' => array('uID' => $params['uid'], 'sID' => $params['sid'])));
    drupal_mail('bg_scriptmachine', 'notify', $params['to_email'], $language, $params);
  }

  return $xml_response;
}

function _bg_scriptmachine_create_error_document($message, $code) {
  $document = new DOMDocument('1.0', 'UTF-8');
  $root = $document->createElement('response');
  $document->appendChild($root);
  $e = $document->createElement('error');
  $root->appendChild($e);
  $e->setAttribute('code', $code);
  $e->appendChild($document->createTextNode(t($message)));
  return $document;
}

function _bg_scriptmachine_create_ok_document() {
  $document = new DOMDocument('1.0', 'UTF-8');
  $root = $document->createElement('response');
  $document->appendChild($root);
  $e = $document->createElement('ok');
  $root->appendChild($e);
  return $document;
}
